### ISSUE TITLE
Open port please :children_crossing:

### ISSUE THREAD

**Issue by matthieuMoisson** [PolytechLyon/cloud-project-equipe-7#7]
@Slashgear can you open the port 27017, 27018, 27019, 28017

**Comment by matthieuMoisson** [comment]
8080 to

**Comment by JoymangulJensen** [comment]
@Slashgear can you please close all the port that you have opened leave only the port 80 open as well as the port for ssh connection to the server.

**Comment by Slashgear** [comment]
Done
